##### Predicting reviewer‘s cabin class based on their written review on Skytrax

In [20]:
import pandas as pd
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import pickle
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from textacy.preprocess import preprocess_text
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from textblob import TextBlob, Word
from nltk.stem.snowball import SnowballStemmer

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [2]:
# we open the file for reading
fileObject1 = open("df_air.pickle",'rb')
fileObject2 = open("df_main.pickle",'rb')
fileObject3 = open("star.pickle",'rb')
fileObject4 = open("budget.pickle",'rb')

# load the object from the file into variables
df_air = pickle.load(fileObject1)  
df = pickle.load(fileObject2) 
star = pickle.load(fileObject3) 
budget = pickle.load(fileObject4) 

In [3]:
df.reset_index(inplace=True)
df.drop(columns=['index'],axis=1,inplace=True)
df.head(50)

airline_name  author_country  \
0              0              54   
1              0             149   
2              0             138   
3              0             129   
4              0             118   
5              0              54   
6              0              51   
7              0             131   
8              0             129   
9              0             131   
10             0             144   
11             0              89   
12             0              27   
13             0             129   
14             0             144   
15             0              51   
16             0              57   
17             0             138   
18             0             148   
19             0             131   
20             0             131   
21             0             131   
22             0               7   
23             0              27   
24             0             148   
25             0             148   
26             0             148   
27             1             149   
28             0             135   
29             0             146   
30             0             138   
31             0              87   
32             1               7   
33             1             148   
34             1              15   
35             1              57   
36             1             149   
37             1              72   
38             1             138   
39             1             148   
40             1              54   
41             1              72   
42             1              27   
43             1             137   
44             1             148   
45             1              27   
46             1             148   
47             1              57   
48             1             148   
49             1             138   

                                              content  cabin_flown  \
0   Outbound flight FRA/PRN A319. 2 hours 10 min f...            1   
1   Two short hops ZRH-LJU and LJU-VIE. Very fast ...            0   
2   Flew Zurich-Ljubljana on JP365 newish CRJ900. ...            1   
3   Adria serves this 100 min flight from Ljubljan...            0   
4   WAW-SKJ Economy. No free snacks or drinks on t...            1   
5   Sarajevo-Frankfurt via Ljubljana. I loved flyi...            1   
6   I had flights from Paris to Sarajevo via Ljubl...            1   
7   LJU to FRA and back both flights were on time....            1   
8   On my Ljubljana - Munich flight in business cl...            0   
9   Flights from LJU to ZRH and back all on time. ...            1   
10  I was very satisfied with the CRJ 900 on my fl...            1   
11  I was on JP650 the evening departure to Istanb...            1   
12  VIE-LJU LJU-MUC Aug 4-15th CRJ200. Both flight...            1   
13  If I have to fly a regional jet then I prefer ...            0   
14  Istanbul-Ljubljana-Munich and return. Pre-take...            0   
15  Return flight Paris-Skopje via Ljubljana. All ...            1   
16  BEG-LJU-BEG with CRJ200 great regional airline...            1   
17  I fly at least once a month ZRH-LJU-ZRH. My ex...            1   
18  LTN to LJU outbound with CRJ200 return with CR...            1   
19  Ljubljana to Brussels with CRJ900. Boarding on...            1   
20  LJU-FRA and FRA-LJU. First flight on time retu...            1   
21  LJU-FRA-LJU. Both flights on time. Flight atte...            1   
22  Smart and efficient service. Small planes but ...            1   
23  FRA-VIE in Business Class. A great little airl...            0   
24  London Gatwick to Ljubljana and Ljubljana to V...            0   
25  ZRH to LJU as a continuation to a flight with ...            1   
26  I fly Adria a lot (at least once a month) and ...            1   
27  Brand new A320, interior spotless. Crew immacu...            1   
28  I fly Adria quite a lot (aprox 2 flts a month)...            1   
29  This was my first time with Adria. Short hop f...            1 

In [4]:
df.columns

Index(['airline_name', 'author_country', 'content', 'cabin_flown',
       'overall_rating', 'seat_comfort_rating', 'cabin_staff_rating',
       'food_beverages_rating', 'inflight_entertainment_rating',
       'ground_service_rating', 'wifi_connectivity_rating',
       'value_money_rating', 'recommend', 'airline', 'cabin_class', 'overall'],
      dtype='object')

In [5]:
y = df['cabin_flown']
#.astype('uint8')

In [6]:
clean_text = [preprocess_text(x, fix_unicode=True, lowercase=True, transliterate=False,
                              no_urls=True, no_emails=True, no_phone_numbers=True, no_currency_symbols=True,
                              no_punct=True, no_accents=True)
              for x in df['content'].values]

#### MULTI-CLASS CLASSIFICATION MODEL

In [7]:
tfv = TfidfVectorizer(ngram_range=(1,2), max_features=50000)
X = tfv.fit_transform((clean_text))

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
rf = RandomForestClassifier(n_estimators=250, verbose=1)
knn = KNeighborsClassifier(n_neighbors=5)

In [10]:
rf.fit(X_train, y_train)
knn.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:  1.8min finished


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [11]:
# Random forest and KNN scores:
print('RF:', rf.score(X_test, y_test))
print('KNN:', knn.score(X_test, y_test))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:    2.8s finished


RF: 0.8846620450606586
KNN: 0.8304159445407279


In [12]:
rf_yhat = rf.predict(X_test)
#rf_yhat = knn.predict(X_test)

print(classification_report(y_test, rf_yhat))
print(confusion_matrix(y_test, rf_yhat))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:    2.9s finished


              precision    recall  f1-score   support

           0       0.83      0.72      0.77      1907
           1       0.89      0.98      0.94      8917
           2       0.92      0.13      0.23       266
           3       0.86      0.08      0.15       450

   micro avg       0.88      0.88      0.88     11540
   macro avg       0.88      0.48      0.52     11540
weighted avg       0.88      0.88      0.86     11540

[[1381  523    0    3]
 [ 154 8757    3    3]
 [  77  154   35    0]
 [  54  360    0   36]]


#### Preparing data for - Predicted cabin class result

In [13]:
y_predict = pd.DataFrame(rf_yhat)
y_predict.columns = ['predicted_class']
y_predict['predicted_class_desc'] = y_predict['predicted_class'].map({1:'Econ',0:'Business',2:'First',3:'Prem'}) 

#### Preparing data for - Tested subset dataset

In [14]:
y_test = df.loc[y_test.index]
y_test.reset_index(inplace=True)

In [15]:
result = pd.concat([y_test, y_predict], axis=1)

In [28]:
result[['content','cabin_flown','cabin_class','predicted_class','predicted_class_desc']].head(55)

content  cabin_flown  \
0   Travelled round trip SIN-ZRH-GVA. All flights ...            1   
1   18th January EY0455 SYD-AUH. Flight back to Sy...            1   
2   Flight to Cape Town from CDG. Booked premium e...            3   
3   Nadi-Auckland Economy on old 747. All seats an...            1   
4   I have used Eastern Airways for a number of ye...            1   
5   TBS-DOH-MXP. Both aircraft's seemed relatively...            1   
6   EK005 7th Jan Business class with my wife and ...            0   
7   Intersky is another airline charging high pric...            1   
8   Jakarta - Kuala Lumpur - Amsterdam - Helsinki ...            1   
9   HKG-CDG Flight 185. FA's were particularly fri...            0   
10  My wife and I travelled business class Sydney ...            0   
11  PRG-CGN-PRG. Check-in at PRG okay. Onboard you...            1   
12  Heathrow to Melbourne in early December and ma...            0   
13  GLA to SOU - Perfect flight took off on time l...            1   
14  Very short flight from Barcelona to Palma (FR ...            1   
15  Crew unfriendly and either don't say anything ...            1   
16  Upon our arrival to Rome from JFK on May 7th w...            1   
17  9W 121 London to Delhi. Flight was scheduled t...            1   
18  I was positively surprised when I recently in ...            1   
19  Island Air got us safely between Honolulu and ...            1   
20  Heathrow to LA in Economy. This was my first a...            1   
21  Incheon to London Heathrow last month and it w...            1   
22  Flew HAN-SGN on an old but clean B777. Flight ...            1   
23  On July 1 2014 travelled with family from JFK ...            1   
24  BA12 15th August 2014. In my mind that when I ...            1   
25  You may think it is a cheap flight - but they ...            1   
26  Internal flight Daegu - Incheon on which my wi...            1   
27  HKG-KUL. The plane is embarrassingly old. My s...            0   
28  Manchester to Dalaman Turkey and return June/J...            1   
29  I flew Ethiopian Airlines as they are a part o...            1   
30  FRA-LCY-FRA on excellent BA Cityflyer - what a...            0   
31  Hong Kong - Seoul - Los Angeles return. All fl...            1   
32  I had booked a trip to Hong Kong through Fligh...            1   
33  LGW to Montego Bay. Premium Cabin The crew wer...            3   
34  I recently has 2 horrible experiences with thi...            1   
35  IAD-ORY return. Dulles lounge was satisfactory...            0   
36  MEL-JFK over three separate legs. Encountered ...            2   
37  IST-Paris CDG Business Class A330-200. Boardin...            0   
38  Flew from Bahrain to Delhi. Flight took off an...            1   
39  Flew LAX-SFO-ORD-LAX last week in First. Had a...            2   
40  QF 98 HKG-BNE on new interior A330. My first f...            1   
41  Warsaw-Copenhagen quick and good service. As a...            1   
42  My wife and I travelled from CPH to EWR via KE...            0   
43  Delayed 9 hours 21 December 2014 from Kilimanj...            0   
44  Bellingham to Vegas got to airport on time but...            1   
45  LHR-BOM-DEL-LHR. Business. Outbound 777-300ER....            0   
46  Flew round trip from Denver to Frankfurt in Ma...            1   
47  I read past reviews and learned that you need ...            1   
48  We traveled home from Las Vegas on Tuesday Jul...            1   
49  Colombo-Muscat-Paris in Business. First leg on...            0   
50  Ground staff for Sydney to Melbourne flight ve...            1   
51  I travelled Manchester - Sydney return on 777-...            0   
52  W63702 and 3701 5th Feb to 12th Feb 2014. I tr...            1   
53  My husband and I flew from Charlotte NC to Chi...            1   
54  KUL-ALA-AKX return. First flight from KUL-ALA ...            1   

        cabin_class  predicted_class predicted_class_desc  
0           Economy                1                 Econ  
1    